### ISSUE TITLE
Difference from OpenVoice

### ISSUE THREAD

**Issue by fakerybakery** [myshell-ai/MeloTTS#1]
Hey, this looks really cool! How is this different from OpenVoice? (And is this the permissively licensed successor?) thanks!

**Comment by Zengyi-Qin** [comment]
The difference is that MeloTTS support more languages and sounds more natural than the current OpenVoice. But it does not support voice cloning. It's under MIT License and permits free commercial use. OpenVoice will also be changed to this license in this Spring

**Comment by fakerybakery** [comment]
Thanks!

**Comment by RonanKMcGovern** [comment]
So the architecture is that of OpenVoice?

**Comment by abu100** [comment]
How does it compare to OpenVoiceV2?

**Comment by fakerybakery** [comment]
> How does it compare to OpenVoiceV2 [fakerybakery](https://github.com/fakerybakery)?

I think the main difference is that OpenVoice V2 supports zero-shot voice cloning

**Comment by abu100** [comment]
And what about audio quality? I am having problem setting both of them up on windows, otherwise I would have tested for myself. 😅

**Comment by fakerybakery** [comment]
> And what about audio quality? I am having problem setting both of them up on windows, otherwise I would have tested for myself. 😅

You should try out the online demos ([OpenVoice](https://huggingface.co/spaces/myshell-ai/OpenVoiceV2)/[MeloTTS](https://huggingface.co/spaces/mrfakename/MeloTTS)) which do not require installation
