### ISSUE TITLE
Failed initializing MeCab.

### ISSUE THREAD

**Issue by dafogary** [myshell-ai/MeloTTS#135]
Hi I just found this repository yesterday, and I like what it says it can do.

But, when I run:

melo-ui --port 9999

Most of it goes OK, but I get the error:

File "/var/www/html/MeloTTS/melo/text/cleaner.py", line 1, in <module>
from . import chinese, japanese, english, chinese_mix, korean, french, spanish
File "/var/www/html/MeloTTS/melo/text/japanese.py", line 367, in <module>
_TAGGER = MeCab.Tagger()
File "/usr/local/lib/python3.10/dist-packages/MeCab/__init__.py", line 135, in __init__
raise RuntimeError(error_info(rawargs)) from ee
RuntimeError: 
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: 
[ifs] no such file or directory: /usr/local/lib/python3.10/dist-packages/unidic/dicdir/mecabrc

I don't really need Japanese, from what I gather, this relates to Japanese, I am just interested in English at the moment.

I have also tried running:

>pip3 install unidic-lite

But, it still doesn't want to work.

Can I disable this, or does anyone know how I can fix it?``

**Comment by louistiti** [comment]
Hi, did you download UniDic?

Try:
```
python -m unidic download
```

**Comment by dafogary** [comment]
That seems to have fixed it, not sure how I missed that, thank you

**Comment by iamsagar99** [comment]
If you are still facing this issue, here is what worked for me and it may help you also.
- ./.venv/bin/python -m unidic download
the .venv is my virtual environment. Then you wont face any import error.
