### ISSUE TITLE
What is the sampling rate of the pre-trained model?

### ISSUE THREAD

**Issue by gansidui** [myshell-ai/MeloTTS#191]
The training document recommends a sampling rate of 44100, but I provide data with a sampling rate of 24000 for training. Will there be any difference in the effect?
I want to keep the sampling rate consistent with the pre-trained model instead of resampling it.

**Comment by justinatbahasa** [comment]
hi @gansidui how's the result training with 24khz audio?

**Comment by gansidui** [comment]
> 你好@gansidui使用 24khz 音频进行训练的效果如何？

The effect is pretty good. During training, 24Khz will be resampled and the final result is still 44100Hz.
