### ISSUE TITLE
Is anyone aware of the looping issue in the trainer?

### ISSUE THREAD

**Issue by KiON-GiON** [myshell-ai/MeloTTS#210]
I think it's how the trainer behaves. However, I'd like to ask if there's a solution to this problem. When all the iterations are complete, the trainer loops, starting from epoch 0 again.

Is there a way to automatically stop the trainer when the specified epochs (i.e. in the config.json file) are complete? I'm experimenting in the cloud, so this will be useful if this can be solved somehow.

**Comment by smlkdev** [comment]
There is infinite while loop in train script:

https://github.com/myshell-ai/MeloTTS/blob/main/melo/train.sh

The solution might be to write some extra code like:

- after every iteration check for file named `G_nnnnn.pth` inside `./melo/logs/...` dir and if you find it then just break the loop
