### ISSUE TITLE
missing installation step "python -m pip install unidic"

### ISSUE THREAD

**Issue by LockMan007** [myshell-ai/MeloTTS#35]
missing installation step "python -m pip install unidic", otherwise you can get:
"No module named unidic"

so the correct code to install in windows is:

git clone https://github.com/myshell-ai/MeloTTS.git
cd MeloTTS
pip install -e .
**python -m pip install unidic**
python -m unidic download

**Comment by Zengyi-Qin** [comment]
This package is already in the requirements.txt

**Comment by rickyzhangca** [comment]
somehow still have to manually run `python -m pip install unidic` to get it to work
