### ISSUE TITLE
MacOS installed though Docker. but docker run error:could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by dcdebug** [myshell-ai/MeloTTS#40]
docker build successfully. my macbookpro is M1 chip.
I run the command :
`sudo docker run --gpus all -it -p 8888:8888 melotts`
then get the error:

```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:
```
Not supported ?

**Comment by Zengyi-Qin** [comment]
Try removing the `--gpus all`

**Comment by dcdebug** [comment]
> Try removing the `--gpus all`

`Thank you, it worked.`
