### ISSUE TITLE
docker 安装错误

### ISSUE THREAD

**Issue by skyliwq** [myshell-ai/MeloTTS#44]
=> ERROR [7/7] RUN python melo/init_downloads.py

56.33 Traceback (most recent call last):
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
56.33     conn = connection.create_connection(
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
56.33     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
56.33   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
56.33     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
56.33 socket.gaierror: [Errno -3] Temporary failure in name resolution
56.33
56.33 During handling of the above exception, another exception occurred:
56.33
56.33 Traceback (most recent call last):
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
56.33     httplib_response = self._make_request(
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
56.33     self._validate_conn(conn)
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
56.33     conn.connect()
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
56.33     self.sock = conn = self._new_conn()
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
56.33     raise NewConnectionError(
56.33 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7feb1ac74100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
56.33
56.33 During handling of the above exception, another exception occurred:
56.33
56.33 Traceback (most recent call last):
56.33   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
56.33     resp = conn.urlopen(
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
56.33     retries = retries.increment(
56.33   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
56.33     raise MaxRetryError(_pool, url, error or ResponseError(cause))
56.33 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Max retries exceeded with url: /repos/8a/1e/8a1ef674c4775bc19ceb0e1b85c7136ea7f9b0157416ed9a7087ac84f4160675/acd278040eaf9536908e2b965273df5a731c44d8f0da66cc5fed7972772ed23c?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27checkpoint.pth%3B+filename%3D%22checkpoint.pth%22%3B&Expires=1709629442&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwOTYyOTQ0Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzhhLzFlLzhhMWVmNjc0YzQ3NzViYzE5Y2ViMGUxYjg1YzcxMzZlYTdmOWIwMTU3NDE2ZWQ5YTcwODdhYzg0ZjQxNjA2NzUvYWNkMjc4MDQwZWFmOTUzNjkwOGUyYjk2NTI3M2RmNWE3MzFjNDRkOGYwZGE2NmNjNWZlZDc5NzI3NzJlZDIzYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=eYWAAm3hnYBgV0BaOM7SO4frDGQwsuROYf46iWBwCoBEjZFDZxI1jHqT6y63pfmLWPcg3FmEObNLA6V7iVq~TtMUDZj7eNJd-iGBaNW9SBWd6WJu6iCPvIgbz1IIyYKu8FdZGGLmuuvveUWVsH2IawLFYep~UkCJeIlo5g~rAYWFZ94Nr9r6Sp8W-Ivf-AA~mx00E1ErGlgLm2K5GmNrSH77DDVJy6k3o01~ysFkDIz2i0ZhsD41RU2Y4DCvbM8wulY9K5SXsyh6uQlCevV1o6YgG0WJwmhKFO7M7naL4UazmexzaTOL-jlakCxhsb-XWYuhy3t9bEYwjqFmJutsTw__&Key-Pair-Id=KCD77M1F0VK2B (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb1ac74100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
56.33
56.33 During handling of the above exception, another exception occurred:
56.33
56.33 Traceback (most recent call last):
56.33   File "/app/melo/init_downloads.py", line 8, in <module>
56.33     'EN': TTS(language='EN', device=device),
56.33   File "/app/melo/api.py", line 57, in __init__
56.33     checkpoint_dict = load_or_download_model(language, device, use_hf=use_hf)
56.33   File "/app/melo/download_utils.py", line 51, in load_or_download_model
56.33     ckpt_path = hf_hub_download(repo_id=LANG_TO_HF_REPO_ID[language], filename="checkpoint.pth")
56.33   File "/usr/local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
56.33     return fn(*args, **kwargs)
56.33   File "/usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
56.33     http_get(
56.33   File "/usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 451, in http_get
56.33     r = _request_wrapper(
56.33   File "/usr/local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
56.33     response = get_session().request(method=method, url=url, **params)
56.33   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
56.33     resp = self.send(prep, **send_kwargs)
56.33   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
56.33     r = adapter.send(request, **kwargs)
56.33   File "/usr/local/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 67, in send
56.33     return super().send(request, *args, **kwargs)
56.33   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
56.33     raise ConnectionError(e, request=request)
56.33 requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Max retries exceeded with url: /repos/8a/1e/8a1ef674c4775bc19ceb0e1b85c7136ea7f9b0157416ed9a7087ac84f4160675/acd278040eaf9536908e2b965273df5a731c44d8f0da66cc5fed7972772ed23c?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27checkpoint.pth%3B+filename%3D%22checkpoint.pth%22%3B&Expires=1709629442&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwOTYyOTQ0Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzhhLzFlLzhhMWVmNjc0YzQ3NzViYzE5Y2ViMGUxYjg1YzcxMzZlYTdmOWIwMTU3NDE2ZWQ5YTcwODdhYzg0ZjQxNjA2NzUvYWNkMjc4MDQwZWFmOTUzNjkwOGUyYjk2NTI3M2RmNWE3MzFjNDRkOGYwZGE2NmNjNWZlZDc5NzI3NzJlZDIzYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=eYWAAm3hnYBgV0BaOM7SO4frDGQwsuROYf46iWBwCoBEjZFDZxI1jHqT6y63pfmLWPcg3FmEObNLA6V7iVq~TtMUDZj7eNJd-iGBaNW9SBWd6WJu6iCPvIgbz1IIyYKu8FdZGGLmuuvveUWVsH2IawLFYep~UkCJeIlo5g~rAYWFZ94Nr9r6Sp8W-Ivf-AA~mx00E1ErGlgLm2K5GmNrSH77DDVJy6k3o01~ysFkDIz2i0ZhsD41RU2Y4DCvbM8wulY9K5SXsyh6uQlCevV1o6YgG0WJwmhKFO7M7naL4UazmexzaTOL-jlakCxhsb-XWYuhy3t9bEYwjqFmJutsTw__&Key-Pair-Id=KCD77M1F0VK2B (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb1ac74100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"), '(Request ID: ccc80f06-1a04-4eca-a0a4-98ec6e9cba50)')
------
Dockerfile:11
--------------------
   9 |     RUN pip install -e .
  10 |     RUN python -m unidic download
  11 | >>> RUN python melo/init_downloads.py
  12 |
  13 |     CMD ["python", "./melo/app.py", "--host", "0.0.0.0", "--port", "8888"]
--------------------

**Comment by xcn700418** [comment]
你好，请问问题解决了吗，我也有相同错误
