### ISSUE TITLE
Quantization for speed boost?

### ISSUE THREAD

**Issue by jadechip** [myshell-ai/MeloTTS#46]
I've been trying to quantize the Linear and Convolutional layers to try and speed up model inference but I am getting mixed results, this is what I am doing at the moment:

```
quantized_model = torch.quantization.quantize_dynamic(
    model,
    {torch.nn.Linear, torch.nn.Conv1d},  # Add other layers as needed
    dtype=torch.qint8,
    inplace=True
)
```

Does anyone have any advice?

**Comment by AngelGuevara7** [comment]
Hi! 
I was thinking about doing quantization also, but I'm a bit lost. Did you find a way to do it?
Thanks!!
