### ISSUE TITLE
docker 安装报错

### ISSUE THREAD

**Issue by bergli2020** [myshell-ai/MeloTTS#53]
报错信息如下
_**_380.7 ERROR: Exception:
380.7 Traceback (most recent call last):
380.7   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
380.7     yield
380.7   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
380.7     data = self._fp_read(amt) if not fp_closed else b""
380.7   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
380.7     return self._fp.read(amt) if amt is not None else self._fp.read()
380.7   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
380.7     data = self.__fp.read(amt)
380.7   File "/usr/local/lib/python3.9/http/client.py", line 463, in read
380.7     n = self.readinto(b)
380.7   File "/usr/local/lib/python3.9/http/client.py", line 507, in readinto
380.7     n = self.fp.readinto(b)
380.7   File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
380.7     return self._sock.recv_into(b)
380.7   File "/usr/local/lib/python3.9/ssl.py", line 1275, in recv_into
380.7     return self.read(nbytes, buffer)
380.7   File "/usr/local/lib/python3.9/ssl.py", line 1133, in read
380.7     return self._sslobj.read(len, buffer)
380.7 socket.timeout: The read operation timed out_**_

**Comment by itcuihao** [comment]
docker error
```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 355B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9-slim
#3 ERROR: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
------
 > [internal] load metadata for docker.io/library/python:3.9-slim:
------
Dockerfile:1
--------------------
   1 | >>> FROM python:3.9-slim
   2 |     WORKDIR /app
   3 |     COPY . /app
--------------------
ERROR: failed to solve: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
```

**Comment by Zengyi-Qin** [comment]
Network issues. Are you using VPN?

**Comment by bergli2020** [comment]
不是VPN，将docker换成国内镜像源就好了

**Comment by bergli2020** [comment]
change the apt and pip source images
