### ISSUE TITLE
Portuguese language

### ISSUE THREAD

**Issue by jersonjunior** [myshell-ai/MeloTTS#7]
Portuguese on roadmap?

**Comment by Zengyi-Qin** [comment]
Hi we current don't have that data. Collecting the dataset takes a lot of time. We are planning to release the training code so that the open-source community can train by themselves

**Comment by Zengyi-Qin** [comment]
https://github.com/myshell-ai/MeloTTS/blob/main/docs/quick_use.md

**Comment by skyliwq** [comment]
> myshell 上有一些模型可能会满足您的需求https://github.com/myshell-ai/MeloTTS/blob/main/docs/quick_use.md。我们还计划发布训练代码供社区训练更多语言

上面模型能下载到本地使用吗

**Comment by paulozip** [comment]
@Zengyi-Qin these Portuguese voice models are really good, but we can't use them, right? I mean for finetuning or training from scratch
