### ISSUE TITLE
How does this compare to coqui?

### ISSUE THREAD

**Issue by Bardo-Konrad** [myshell-ai/MeloTTS#90]
How does this compare to coqui?

**Comment by AngelGuevara7** [comment]
You can check it here: https://huggingface.co/spaces/TTS-AGI/TTS-Arena

**Comment by Bardo-Konrad** [comment]
coqui is not on the list

**Comment by AngelGuevara7** [comment]
XTTSv2 is coqui right?

**Comment by Bardo-Konrad** [comment]
I see.
